name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
          path: ./.v

      - name: Build local V
        run: cd ./.v && make && sudo ./v symlink

      - name: Generate docs
        run: v doc -o ./docs -f html .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs
