name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.01
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: vlang/setup-v@v1
        with:
          token: ${{ github.token }}
          version: 'weekly.2022.16'

      - name: Generate docs
        run: v doc -o ./docs -f html .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs
